 [project]
name = "Admitix-backend"
version = "0.1.0"
description = "Admitix Backend API"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.5",
    "asyncpg>=0.31.0",
    "bcrypt>=5.0.0",
    "email-validator>=2.3.0",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "orjson>=3.11.9",
    "passlib>=1.7.4",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.2",
    "python-dotenv>=1.2.2",
    "python-jose>=3.5.0",
    "python-multipart>=0.0.32",
    "pymupdf>=1.26.4",
    "pillow>=11.3.0",
    "psycopg2-binary>=2.9.10",
    "sqlalchemy>=2.0.51",
    "uvicorn>=0.52.1",
    "pytesseract>=0.3.13",
]

[tool.uv]
package = false
